//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probando_breeze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Edad { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.Guid> Matricula { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual Matricula Matricula1 { get; set; }
    }
}
